# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simple IO Pages
email: mhyeon.lee@navercorp.com
description: > # this means to ignore newlines until "baseurl:"
  개발 이야기
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mhyeon-lee.github.io" # the base hostname & protocol for your site
twitter_username: mhyeon-lee
github_username:  mhyeon-lee

# Build settings
markdown: kramdown
