title: mhyeon-lee blog
description: > # this means to ignore newlines until "baseurl:"
  Developer
permalink: ':title/'
baseurl: "https://mhyeon-lee.github.io" # the subpath of your site, e.g. /blog
url: "https://mhyeon-lee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Myeonghyeon Lee # add your name
author-img: david-freeman.jpg # add your photo
about-author: Developer. # add description
social-twitter: # add your Twitter handle
social-facebook: https://www.facebook.com/profile.php?id=100001657490462 # add your Facebook handle
social-github: mhyeon-lee # add your Github handle
social-linkedin: https://www.linkedin.com/in/myeonghyeon-lee-68934985 # add your Linkedin handle
social-email: mhyeon.lee@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
